apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Tells Kustomize to fetch the schema from the active cluster context
resources:
  - coredns-patch.yaml

# 2. Instructs Kustomize to execute the merge operation
patches:
  - path: coredns-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: coredns
      namespace: kube-system
